
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'*y\x97)q\xabs\x02\xe9\x02\xb7\xba\xf5\xb9\xef\xd5'
    
_lr_action_items = {'WORD':([1,2,3,5,7,8,9,10,11,12,13,14,],[5,6,-3,8,-2,-7,-9,8,-8,-6,-5,-4,]),';':([8,9,10,11,12,13,],[-7,-9,14,-8,-6,-5,]),':':([0,2,3,7,14,],[1,1,-3,-2,-4,]),'$end':([4,6,],[0,-1,]),'INT_LIT':([5,8,9,10,11,12,13,],[11,-7,-9,11,-8,-6,-5,]),'STR_LIT':([5,8,9,10,11,12,13,],[9,-7,-9,9,-8,-6,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'definitions':([0,],[2,]),'definition':([0,2,],[3,7,]),'program':([0,],[4,]),'statement':([5,],[10,]),'element':([5,10,],[12,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> definitions WORD','program',2,'p_program','forthtobf/forth2bf.py',58),
  ('definitions -> definitions definition','definitions',2,'p_definitions','forthtobf/forth2bf.py',62),
  ('definitions -> definition','definitions',1,'p_definitions_definition','forthtobf/forth2bf.py',66),
  ('definition -> : WORD statement ;','definition',4,'p_definition','forthtobf/forth2bf.py',70),
  ('statement -> statement element','statement',2,'p_statement','forthtobf/forth2bf.py',74),
  ('statement -> element','statement',1,'p_statement_word','forthtobf/forth2bf.py',78),
  ('element -> WORD','element',1,'p_element_word','forthtobf/forth2bf.py',82),
  ('element -> INT_LIT','element',1,'p_element_int','forthtobf/forth2bf.py',86),
  ('element -> STR_LIT','element',1,'p_element_str','forthtobf/forth2bf.py',90),
]
